### PR TITLE
Remove pdftk, since poppler aleady includes pdfseparate

### PR DESCRIPTION
**Pull request by gcpantazis**
Might as well use other poppler tools! :)

This seems to pass all tests on my end; let me know if you see any issue with this.

### CODE REVIEW

**Comment by gcpantazis** [comment]
@nisaacson worth merging this? I'm trying to clean out my old PRs.

**Comment by nisaacson** [comment]
thanks for this change. @gcpantazis If you are willing to rebase I will merge this in. Sorry for the delay in getting to this PR

**Comment by gcpantazis** [comment]
Thanks @nisaacson, no worries. I'll clean it up this weekend most likely 👍

**Comment by gcpantazis** [comment]
Got too far removed from this; hope the branch is useful if anyone else wants to take this up. :)

**Pull request closed without merging**
